#define BASE_1_1 LT(_ART_SYM,KC_A)
#define BASE_1_2 KC_R
#define BASE_1_3 KC_T
#define BASE_1_4 LT(_ART_NUM,KC_S)
#define BASE_2_1 LT(_ART_PUNC,KC_E)
#define BASE_2_2 DE_Y
#define BASE_2_3 KC_I
#define BASE_2_4 LT(_ART_CUS,KC_O)
#define NUM_1_1 KC_1
#define NUM_1_2 KC_2
#define NUM_1_3 KC_3
#define NUM_1_4 KC_TRNS
#define NUM_2_1 KC_4
#define NUM_2_2 KC_5
#define NUM_2_3 KC_6
#define NUM_2_4 KC_TRNS
#define PUNC_1_1 DE_HASH
#define PUNC_1_2 DE_GRV
#define PUNC_1_3 DE_SCLN
#define PUNC_1_4 DE_BSLS
#define PUNC_2_1 KC_TRNS
#define PUNC_2_2 DE_AT
#define PUNC_2_3 DE_MINS
#define PUNC_2_4 DE_EQL
#define CUS_1_1 KC_MPLY
#define CUS_1_2 KC_MUTE
#define CUS_1_3 KC_VOLU
#define CUS_1_4 KC_TRNS
#define CUS_2_1 KC_MPRV
#define CUS_2_2 KC_MNXT
#define CUS_2_3 KC_VOLD
#define CUS_2_4 KC_TRNS
#define SYM_1_1 KC_TRNS
#define SYM_1_2 DE_LPRN
#define SYM_1_3 DE_LBRC
#define SYM_1_4 DE_LCBR
#define SYM_2_1 KC_TRNS
#define SYM_2_2 DE_RPRN
#define SYM_2_3 DE_RBRC
#define SYM_2_4 DE_RCBR
#define MOU_1_1 KC_BTN1
#define MOU_1_2 KC_MS_U
#define MOU_1_3 KC_BTN2
#define MOU_1_4 KC_WH_U
#define MOU_2_1 KC_MS_L
#define MOU_2_2 KC_MS_D
#define MOU_2_3 KC_MS_R
#define MOU_2_4 KC_WH_D
#define NAV_1_1 KC_HOME
#define NAV_1_2 KC_UP
#define NAV_1_3 KC_END
#define NAV_1_4 KC_PGUP
#define NAV_2_1 KC_LEFT
#define NAV_2_2 KC_DOWN
#define NAV_2_3 KC_RIGHT
#define NAV_2_4 KC_PGDN
